// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaLocLab.Infrastructure.Context;

#nullable disable

namespace SistemaLocLab.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526000248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisciplinaSoftware", b =>
                {
                    b.Property<Guid>("DisciplinasIdDisciplina")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SoftwaresIdSoftware")
                        .HasColumnType("uuid");

                    b.HasKey("DisciplinasIdDisciplina", "SoftwaresIdSoftware");

                    b.HasIndex("SoftwaresIdSoftware");

                    b.ToTable("DisciplinaSoftware");
                });

            modelBuilder.Entity("LaboratoriosSoftware", b =>
                {
                    b.Property<Guid>("LaboratoriosIDLaboratorio")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SoftwaresIdSoftware")
                        .HasColumnType("uuid");

                    b.HasKey("LaboratoriosIDLaboratorio", "SoftwaresIdSoftware");

                    b.HasIndex("SoftwaresIdSoftware");

                    b.ToTable("LaboratoriosSoftware");
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Alocacao", b =>
                {
                    b.Property<Guid>("IdAlocacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DisciplinaId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("IdAlocacao");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("LaboratorioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alocacoes", (string)null);
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Disciplina", b =>
                {
                    b.Property<Guid>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeDisciplina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QtdeAlunos")
                        .HasColumnType("integer");

                    b.HasKey("IdDisciplina");

                    b.ToTable("Disciplinas", (string)null);
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Laboratorios", b =>
                {
                    b.Property<Guid>("IDLaboratorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroLaboratorio")
                        .HasColumnType("integer");

                    b.Property<int>("capacidadeMaxAluno")
                        .HasColumnType("integer");

                    b.Property<int>("qtdeComputador")
                        .HasColumnType("integer");

                    b.HasKey("IDLaboratorio");

                    b.ToTable("Laboratorios", (string)null);
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Software", b =>
                {
                    b.Property<Guid>("IdSoftware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeSoftware")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdSoftware");

                    b.ToTable("Softwares", (string)null);
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Usuarios", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("RE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("DisciplinaSoftware", b =>
                {
                    b.HasOne("SistemaLocLab.Domain.Entities.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("DisciplinasIdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLocLab.Domain.Entities.Software", null)
                        .WithMany()
                        .HasForeignKey("SoftwaresIdSoftware")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LaboratoriosSoftware", b =>
                {
                    b.HasOne("SistemaLocLab.Domain.Entities.Laboratorios", null)
                        .WithMany()
                        .HasForeignKey("LaboratoriosIDLaboratorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLocLab.Domain.Entities.Software", null)
                        .WithMany()
                        .HasForeignKey("SoftwaresIdSoftware")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Alocacao", b =>
                {
                    b.HasOne("SistemaLocLab.Domain.Entities.Disciplina", "Disciplina")
                        .WithMany("Alocacoes")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLocLab.Domain.Entities.Laboratorios", "Laboratorio")
                        .WithMany("Alocacoes")
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLocLab.Domain.Entities.Usuarios", "Usuario")
                        .WithMany("Alocacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Laboratorio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Disciplina", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Laboratorios", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("SistemaLocLab.Domain.Entities.Usuarios", b =>
                {
                    b.Navigation("Alocacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
